spring:
  application:
    name: interview-assistant
  datasource:
    url: jdbc:postgresql://localhost:15432/interview_assistant
    driverClassName: org.postgresql.Driver
    username: ssm_interview_assistant
    password: ssm_interview_assistant
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 16379
      password: ssm_interview_assistant

server:
  port: 9201
  servlet:
    context-path: /${spring.application.name}

springdoc:
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /openapi-doc.html

logging:
  config: classpath:logback-spring.xml

ai:
  global:
    apikey: sk-dcb1d6512f0f4136bbfc3c13b1d84795
    model: deepseek-chat
    base-url: https://api.deepseek.com
  reason:
    model: deepseek-reasoner